### ISSUE TITLE
The rule should not report error for email address

### ISSUE THREAD

**Issue by amimas** [parthpp/textlint-rule-no-dead-relative-link#3]
This rule is currently reporting email address as an invalid relative link.

Here's my markdown sample:

```markdown
Send an email to [our support team](mailto:support@example.com) to request access.
```

This produces the following error:

```text
  64:48  error    mailto:support@example.com is dead. (only http(s) protocols are supported)  no-dead-link
```

I think the rule should ignore email addresses instead of blocking it since this rule is not responsible for validating email addresses.

**Comment by parthpp** [comment]
This issue is not related to this rule but it is related to [textlint-rule-no-dead-link](https://github.com/textlint-rule/textlint-rule-no-dead-link) and it seems to have been [fixed](https://github.com/textlint-rule/textlint-rule-no-dead-link/issues/112). Please update textlint-rule-no-dead-link to [release 4.4.2](https://github.com/textlint-rule/textlint-rule-no-dead-link/releases/tag/4.4.2).
